name: ci-v4.x

on:
  #push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
          base_img:
          - "adoptopenjdk/openjdk8:jdk8u442-b06-debian"
          - "eclipse-temurin:8u442-b06-jdk-noble"
          - "eclipse-temurin:21.0.6_7-jdk-noble"
          vers:
          - "4.9.8"
          - "4.9.7"
          - "4.9.6"
          - "4.9.5"
          - "4.9.4"
          - "4.9.3"
          - "4.9.2"
          - "4.9.1"
          - "4.9.0"
          - "4.8.0"
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"
      - name: Build dockerfile (without push)
        run: |
          ./buildx.sh --push false --repo ${{ secrets.DOCKER_USERNAME }} --base ${{ matrix.base_img }} --version ${{ matrix.vers }}

      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build dockerfile (with push)
        run: |
          ./buildx.sh --push true --repo ${{ secrets.DOCKER_USERNAME }} --base ${{ matrix.base_img }} --version ${{ matrix.vers }}
